openapi: 3.0.1
info:
  title: Desafio Técnico BackEnd - Grupo SBF
  description: Conversor de moedas para produtos esportivos e adição de nova região baseado no "currency code".
  version: 0.0.1
  contact:
    name: Armando N Junior
    email: armandojrn@hotmail.com
    url: https://www.linkedin.com/in/armandojrn/
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.pt-br.html
externalDocs:
  description: github project repository
  url: https://github.com/ArmandoJunior/eng-gruposbf-backend-php
servers:
  - url: http://localhost/api
    description: API - Ambiente de desenvolvimento
paths:
  /products:
    get:
      summary: Recupera todos os produtos
      tags:
        - Products
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
                  links:
                    type: object
                    properties:
                      url:
                        type: string
                        example: "http://localhost/api/products?page=2"
                      label:
                        type: string
                      active:
                        type: boolean
                  path:
                    type: string
                  par_page:
                    type: integer
                  to:
                    type: integer
                  total:
                    type: integer
  /products/{id}:
    get:
      summary: Recupera um produto pelo seu Id
      tags:
        - Products
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    example: "Product not found"
  /prices:
    get:
      summary: "Recupera todos os preços das regiões cadastradas no sistema"
      tags:
        - Prices
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"
    post:
      summary: "Insere uma nova região baseado no currency_code da região"
      tags:
        - Prices
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_code:
                  type: string
                  minLength: 3
                  maxLength: 3
                  example: BRL
                territory:
                  type: string
                  minLength: 3
                  maxLength: 40
                  example: Brasil
      description: "É necessário inserir um currency_code válido (ISO 4217), veja uma lista no link abaixo."
      externalDocs:
        url: https://taxsummaries.pwc.com/glossary/currency-codes
      responses:
        201:
          description: Criado com Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        currency_code:
                          type: string
                        reference_base_value:
                          type: number
                        reference_conversion_value:
                          type: string
                        territory:
                          type: string
                        updated_at:
                          type: string
        422:
          description: Os dados fornecidos são inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    example: "The given data was invalid."
                  errors:
                    example: "The currency code has already been taken."
  /prices/renew:
    get:
      summary: "Renova todos os preços das regiões cadastradas no sistema"
      tags:
        - Prices
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"
  /prices/update:
    get:
      summary: "Faz um update no campo territory de todos os Prices para efeito de teste do uso de cache no sistema, o cache está com o TTL configurado para 1min"
      tags:
        - Prices
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        brand:
          type: string
          example: Nike
        gender:
          type: string
          enum: [masculino, feminino, unisex]
        category:
          type: string
          example: Tênis
        model:
          type: string
          example: Air Max
        amount:
          type: string
          example: "599,90"
        prices:
          type: array
          items:
            type: object
            properties:
              currency_code:
                type: string
                example: BRL
              value:
                type: string
                format: currency
                example: "1,00"
              territory:
                type: string
                example: Brasil
              price_description:
                type: string
                example: "BRL: 1,00 (Brasil)"
    Price:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              currency_code:
                type: string
                example: "BRL"
              reference_base_value:
                type: number
                example: 1
              reference_conversion_value:
                type: string
                example: "0.19"
              territory:
                type: string
                example: "Índia"
              created_at:
                type: string
                format: date
                example: "2022-02-20T11:41:01.000000Z"
              updated_at:
                type: string
                format: date
                example: "2022-02-20T11:49:01.000000Z"
tags:
  - name: Products
    description: Buscar todos os produtos ou um produto específico pelo seu id

  - name: Prices
    description: Buscar todos os prices ou incluir um novo
