name: Laravel build
on: [push]

jobs:
  build:
    name: Laravel build application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-framework
      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phpunit
